---
title: "D'Antonio Lab Pipeline"
author: "Zoe Fung"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install/load packages
library(tidyverse)
library(readr)
library(janitor)
library(here)
library(lubridate)
library(ggplot2)
```

# Importing Data
## Enter your data files here
```{r}
midland_leaf_traits <- "midland_leaf_traits - Sheet1.csv" # leaf traits datasheet
biomass <-  "midland_biomass - Litter.csv" # biomass datasheet
branches <-  "midland_branches - branches.csv" # branches datasheet
```

## Import data file into R
```{r}
leaf_traits <- read_csv(midland_leaf_traits) %>% # read in Midland leaf traits csv file
  clean_names() %>% # standardize column header names
  mutate(date=ymd(date)) %>% # tell R "date" is a DATE
  mutate(as.numeric(curling_mm)) # make curling a numeric vector
```
# Clean up data set/generate summary stats
```{r}
species_clean <- leaf_traits$species # make a vector from the species column
species_clean <- as.character(species_clean) # make "species_clean" a character
species_clean <- species_clean %>%
  str_remove_all("[_0123456789]") %>% # remove the number/_ characters from the species names
  str_replace_all(c("ARTCAL"="ARCA", "HEARNA"="HEAR", "QUAGNA"="QUAG", "ARCAL"="ARCA", "QUDONA"="QUDO")) # standardize the data column with species names 
leaf_traits <- leaf_traits %>%
  add_column(species_cleaned=species_clean) %>% # add species without numbers to dataset
  slice(-145) # delete the row with "NA" for leaf traits
curling_summary <- leaf_traits %>% # create data frame for summary stats of leaf curling
  group_by(species_cleaned) %>% # group the summary stats by species
  summarise(
    n=n(), # sample size
    mean=mean(curling_mm), # mean
    sd=sd(curling_mm) # std. deviation
  )
var1 <- rep("curling", times=7) # create vector with 12 values "curling"
curling_summary <- curling_summary %>%
  add_column(trait=var1) # add "curling" vector to curling summary data frame
thickness_summary <- leaf_traits %>% # create data frame for summary stats of leaf thickness
  group_by(species_cleaned) %>% # group the summary stats by species
  summarise(
    n=n(), # sample size
    mean=mean(thickness_mm), # mean
    sd=sd(thickness_mm) # std. deviation
  )
var2 <- rep("thickness", times=7) # create vector with 12 values "curling"
thickness_summary <- thickness_summary %>%
  add_column(trait=var2) # add "curling" vector to curling summary data frame

mass_summary <- leaf_traits %>% # create data frame for summary stats of leaf mass
  group_by(species_cleaned) %>% # group the summary stats by species
  summarise(
    n=n(), # sample size
    mean=mean(mass_g), # mean
    sd=sd(mass_g) # std. deviation
  )
var3 <- rep("mass", times=7) # create vector with 12 values "curling"
mass_summary <- mass_summary %>%
  add_column(trait=var3) # add "curling" vector to curling summary data frame

leaf_traits_summary <- bind_rows(curling_summary, thickness_summary, mass_summary) # combine the three data sets 
```

# Create standardized .csv
```{r}
write_csv(leaf_traits,paste("leaf_traits",".csv",sep="")) # create .csv with standardized column headers
```

# Graphs
## Bar charts
```{r}
ggplot(curling_summary, aes(x=species_cleaned, y=mean)) + # create plot of species x curling
  geom_bar(stat="identity", fill="plum4") + # plot = bar plot
  xlab("Species") + # x-axis label
  ylab("Curling(mm)") + # y-axis label
  geom_errorbar(aes(x=species_cleaned, ymin=mean-sd, ymax=mean+sd), color="black") # add error bars
ggplot(thickness_summary, aes(x=species_cleaned, y=mean)) + # create plot of species x thickness
  geom_bar(stat="identity", fill="plum4") + # plot = bar plot
  xlab("Species") + # x-axis label
  ylab("Thickness (mm)") + # y-axis label
  geom_errorbar(aes(x=species_cleaned, ymin=mean-sd, ymax=mean+sd), color="black") # add error bars
ggplot(mass_summary, aes(x=species_cleaned, y=mean)) + # create plot of species x mass
  geom_bar(stat="identity", fill="plum4") + # plot = bar plot
  xlab("Species") + # x-axis label
  ylab("Mass (g)") + # y-axis label
  geom_errorbar(aes(x=species_cleaned, ymin=mean-sd, ymax=mean+sd), color="black") # add error bars
ggplot(leaf_traits_summary, aes(x=species_cleaned, y=mean)) + # create plot of species x all traits
  geom_bar(stat="identity", fill="plum4") + # plot = bar plot
  xlab("Species") + # x-axis label
  ylab("Mass (g)") + # y-axis label
  geom_errorbar(aes(x=species_cleaned, ymin=mean-sd, ymax=mean+sd), color="black") # add error bars)
```

## Boxplots
```{r}
ggplot(leaf_traits, aes(x=as.factor(species_cleaned), y=curling_mm)) + # create plot of species x curling
  geom_boxplot(fill="plum4") + # plot = box plot 
  xlab("Species") + # x-axis label
  ylab("Curling (mm)") # y-axis label
ggplot(leaf_traits, aes(x=as.factor(species_cleaned), y=thickness_mm)) + # create plot of species x curling
  geom_boxplot(fill="plum4") + # plot = box plot 
  xlab("Species") + # x-axis label
  ylab("Thickness (mm)") # y-axis label
ggplot(leaf_traits, aes(x=as.factor(species_cleaned), y=mass_g)) + # create plot of species x curling
  geom_boxplot(fill="plum4") + # plot = box plot 
  xlab("Species") + # x-axis label
  ylab("Mass (g)") # y-axis label
```